#+html_head: <link rel="stylesheet" type="text/css" href="../site/style.css">
#+html_head: <link rel="shortcut icon" type="image/x-icon" href="../site/favicon.ico?">
#+options: toc:nil num:nil ^:{} \n:nil ::t -:t ::t html-postamble:nil
#+title: Hassan McGinnis Résumé
#+macro: MATLAB @@html:<span style="font-variant: small-caps;">@@Matlab@@html:</span>@@

* Hassan McGinnis
:PROPERTIES:
:VISIBILITY: children
:HTML_CONTAINER_CLASS: section title
:CUSTOM_ID: name
:END:
*Software* *&* *Controls Engineer* \\
Natick, MA \\

* 
:PROPERTIES:
:VISIBILITY: children
:END:
# --------------
  
** Summary
:PROPERTIES:
:HTML_CONTAINER_CLASS: section
:CUSTOM_ID: summary
:END:      

Software engineer with a background in control systems engineering. Experience developing and testing surgical robotic control software in {{{MATLAB}}}, Simulink, Python, and C++. Familiarity with medical device standards ISO-13485, ISO-14971, and IEC-62304.


** Contact
:PROPERTIES:
:HTML_CONTAINER_CLASS: section
:CUSTOM_ID: contact
:END:      
   
~hassan.mcginnis@gmail.com~ \bullet [[https://www.linkedin.com/in/hrmcginnis][linkedin.com/in/hrmcginnis]] \bullet [[https://hrmcginnis.github.io][hrmcginnis.github.io]]


** Software Skills
:PROPERTIES:
:HTML_CONTAINER_CLASS: section
:CUSTOM_ID: software-skills
:END:      
   
*Languages*: {{{MATLAB}}}, Python, Bash, C++

*Tools & Environments*: {{{MATLAB}}}, Simulink, Stateflow, GNU/Linux, Git, Emacs


** Projects
:PROPERTIES:
:HTML_CONTAINER_CLASS: section notext
:CUSTOM_ID: project1
:END:      
*** 
:PROPERTIES:
:HTML_CONTAINER_CLASS: col notext
:END:      
**** *MedAcuity Software*: Controls Software Verification for Robotic Assisted Surgery System
:PROPERTIES:
:CUSTOM_ID: medacuity-software-verification
:END:      

/Aug 2017 - present/
    
+ Created and implemented a strategy for verification and MC/DC test coverage of state machines and control algorithms for robotic arm motion implemented in Simulink.
+ Led a team of remote test engineers through verification of functional and non-functional software requirements implemented in Simulink and C++.
+ Developed and validated a Python framework and Bamboo test plan for batch execution of C++ requirements tests and Simulink unit tests.
** 
:PROPERTIES:
:HTML_CONTAINER_CLASS: section notext
:CUSTOM_ID: project2
:END:
*** 
:PROPERTIES:
:HTML_CONTAINER_CLASS: col notext
:END:
**** *MathWorks*: Python System Object for Simulink Support Package for Raspberry Pi
:PROPERTIES:
:CUSTOM_ID: mathworks-python-system-object
:END:      
    
/May 2016/

+ Developed a {{{MATLAB}}} system object/Simulink block for the Raspberry Pi support package that interfaces with the Python/C API, enabling simulation data to be streamed to a Python application on the Raspberry Pi in soft real-time.
+ Created a proof of concept demo using the Python System object block in Simulink to drive a servomotor with a Raspberry Pi using the RaspiRobot Python library.
   
** 
:PROPERTIES:
:HTML_CONTAINER_CLASS: section notext
:CUSTOM_ID: project3
:END:
*** 
:PROPERTIES:
:HTML_CONTAINER_CLASS: col notext
:END:
**** *Purdue University*: Sensitivity analysis of wear prognosis in an $H_{\infty}$ controlled F-16 simulation
:PROPERTIES:
:CUSTOM_ID: purdue-h-infinity-control
:END:      
    
/Aug 2010 - Dec 2011/

+ Investigated the minimization of fault propagation in a hydraulic actuator through real-time adjustment in the commanded flight path.
+ Developed a robust altitude controller for an F-16 fighter aircraft model using $H_{\infty}$ synthesis.
+ Performed sensitivity analysis of the path adjustment algorithm under modeling error.
+ Demonstrated the improved control strategy using a hydraulic solenoid valve hardware-in-the-loop system prototyped in Simulink and driven by dSPACE software.


** Work Experience
:PROPERTIES:
:HTML_CONTAINER_CLASS: section notext
:CUSTOM_ID: work-experience
:END:
*** 
:PROPERTIES:
:HTML_CONTAINER_CLASS: col notext
:END:
**** *MedAcuity Software: Westford, MA
:PROPERTIES:
:HTML_CONTAINER_CLASS:
:CUSTOM_ID: medacuity-software-software-specialist
:END:

Test Automation Engineer - /July 2017 - present/
    
**** *MathWorks*: Natick, MA
:PROPERTIES:
:HTML_CONTAINER_CLASS:
:CUSTOM_ID: mathworks-senior-application-engineer-post-sales
:END:

Senior Application Engineer (Post-Sales) /Sept 2013 - July 2016/

Application Support Engineer /Sept 2011 - Sept 2013/


** Education
:PROPERTIES:
:HTML_CONTAINER_CLASS: section notext
:CUSTOM_ID: education
:END:      
*** 
:PROPERTIES:
:HTML_CONTAINER_CLASS: col notext
:END:
   
**** *Purdue University*
:PROPERTIES:
:CUSTOM_ID: purdue-university
:END:      
    
MS Mechanical Engineering - /Dec 2011/ - GPA: /3.81/4.00/

**** *University of Kentucky*
:PROPERTIES:
:CUSTOM_ID: university-of-kentucky
:END:      
    
​BS Mechanical Engineering - /May 2009/ - GPA: /3.46/4.00/ 


** Additional Info
:PROPERTIES:
:HTML_CONTAINER_CLASS: section
:CUSTOM_ID: resume-in-org-mode
:END:      
HTML generated with Emacs using [[https://orgmode.org/][Org Mode]] 
